force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <description>Soccer match</description>
    <label>Match</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/HomeTeam__c.field-meta.xml
<CustomField>
    <fullName>HomeTeam__c</fullName>
    <label>HomeTeam</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team must have 11 active players.</errorMessage>
        <filterItems>
            <field>Team__c.TotalActivePlayers__c</field>
            <operation>equals</operation>
            <value>11</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/PreviousMatchBetweenTeamsDatetime__c.field-meta.xml
<CustomField>
    <fullName>PreviousMatchBetweenTeamsDatetime__c</fullName>
    <label>PreviousMatchBetweenTeamsDatetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>StartDateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Visitors__c.field-meta.xml
<CustomField>
    <fullName>Visitors__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visitors</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team must have 11 active players.</errorMessage>
        <filterItems>
            <field>Team__c.TotalActivePlayers__c</field>
            <operation>equals</operation>
            <value>11</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Visitors)</relationshipLabel>
    <relationshipName>Matches1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Winner__c.field-meta.xml
<CustomField>
    <fullName>Winner__c</fullName>
    <formula>IF( LEFT( Score__c , 1)  &gt;  RIGHT( Score__c , 1)  ,  HomeTeam__r.Name  ,
IF( LEFT( Score__c , 1)  &lt;  RIGHT( Score__c , 1)  ,  Visitors__r.Name ,
IF( LEFT( Score__c , 1)  =  RIGHT( Score__c , 1)  ,  &apos;Draw&apos;  ,
NULL)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Winner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>The team where the player makes his duties</description>
    <label>Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/TotalWins__c.field-meta.xml
<CustomField>
    <fullName>TotalWins__c</fullName>
    <description>Total wins of the team</description>
    <label>TotalWins</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MatchTriggerHandler.cls
public with sharing class MatchTriggerHandler {

    public static void onBeforeInsert(List<Match__c> newMatchesList){
		List<Match__c> listForUpdate = new List<Match__c>();

        Set<Id> teamIdsSet = new Set<Id>();
        for(Match__c match : newMatchesList){
            teamIdsSet.add(match.HomeTeam__c);
            teamIdsSet.add(match.Visitors__c);
        }

        List<Match__c> relatedMatchesToUpdate = [
            SELECT Id, Name, StartDatetime__c, Visitors__c, HomeTeam__c  
            FROM Match__c 
            WHERE Visitors__c IN: teamIdsSet OR HomeTeam__c IN:teamIdsSet
            ORDER BY StartDatetime__c ASC
        ];

        Map<String, List<Match__c>> teamsMemmberToMatches = new Map<String, List<Match__c>>();
        
        for(Match__c match : relatedMatchesToUpdate){
			String key1 = match.Visitors__c + ' - ' + match.HomeTeam__c;
			String key2 = match.HomeTeam__c + ' - ' + match.Visitors__c;
        	if (!teamsMemmberToMatches.containsKey(key1)) {
				teamsMemmberToMatches.put(key1, new List<Match__c>()); 
				teamsMemmberToMatches.put(key2, new List<Match__c>()); 
			} else {
				teamsMemmberToMatches.get(key1).add(match);
				teamsMemmberToMatches.get(key2).add(match);
			}  
        }

		for(Match__c newMatch : newMatchesList){
			String key = newMatch.Visitors__c + ' - ' + newMatch.HomeTeam__c;
			
			if (teamsMemmberToMatches.containsKey(key)) {
				
				List<Match__c> listRealedToThis = teamsMemmberToMatches.get(key);
                Id previousMatch = null;
                DateTime previuosDateTime;
                if (listRealedToThis.size() > 1) { 
                    previuosDateTime = listRealedToThis.get(0).StartDatetime__c;
                    previousMatch = listRealedToThis.get(0).Id;
                }
                system.debug('Test : ' + listRealedToThis);
				for (Match__c matchItem: listRealedToThis) {
                    system.debug('Test : ' + previuosDateTime + ' < ' + matchItem.StartDatetime__c + '  < ' + newMatch.StartDatetime__c);
					if ((previuosDateTime < matchItem.StartDatetime__c) && (matchItem.StartDatetime__c < newMatch.StartDatetime__c)) {
						previuosDateTime = matchItem.StartDatetime__c;
						previousMatch = matchItem.Id;
					}
				}
				if (previousMatch != null) {
                    system.debug('Test : ' + previuosDateTime);
					newMatch.PreviousMatchBetweenTeamsDatetime__c = previuosDateTime;
				}
			}
		}
    }
    
    public static void onAfterUpdate(List<Match__c> newMatches) {
        Set<Id> teamsId = new Set<Id>();

        for(Match__c match : newMatches){
            teamsId.add(match.HomeTeam__c);
            teamsId.add(match.Visitors__c);
        }

        List<Team__c> teamsList = [SELECT Id, Name, TotalWins__c FROM Team__c WHERE Id IN: teamsId];
        Map<String, Team__c> teamNameIdMap = new Map<String, Team__c>();

        for(Team__c team : teamsList){
            teamNameIdMap.put(team.Name, team);
        }

        List<Team__c> updatedTeamsList = new List<Team__c>();

        for(Match__c match : newMatches){
            if(match.Winner__c != 'Draw'){
                updatedTeamsList.add(new Team__c(Id = teamNameIdMap.get(match.Winner__c).Id, TotalWins__c = teamNameIdMap.get(match.Winner__c).TotalWins__c + 1));
            }
        }

        update updatedTeamsList;
    }
}