force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <description>Soccer match</description>
    <label>Match</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/HomeTeam__c.field-meta.xml
<CustomField>
    <fullName>HomeTeam__c</fullName>
    <label>HomeTeam</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team must have 11 active players.</errorMessage>
        <filterItems>
            <field>Team__c.TotalActivePlayers__c</field>
            <operation>equals</operation>
            <value>11</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>StartDateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Visitors__c.field-meta.xml
<CustomField>
    <fullName>Visitors__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visitors</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team must have 11 active players.</errorMessage>
        <filterItems>
            <field>Team__c.TotalActivePlayers__c</field>
            <operation>equals</operation>
            <value>11</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Visitors)</relationshipLabel>
    <relationshipName>Matches1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/upcomingMatchesLWC.cls
public with sharing class upcomingMatchesLWC {

    @AuraEnabled(cacheable=true)
    public static List<Match__c> getMatches(Id currentRecordId){
        return [SELECT Name, StartDateTime__c 
                FROM Match__c 
                WHERE StartDateTime__c >: Datetime.now() AND (HomeTeam__c =: currentRecordId OR Visitors__c =: currentRecordId)
                ORDER BY StartDateTime__c
        ];
    }
}