force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <description>Soccer match</description>
    <label>Match</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/HomeTeam__c.field-meta.xml
<CustomField>
    <fullName>HomeTeam__c</fullName>
    <label>HomeTeam</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team must have 11 active players.</errorMessage>
        <filterItems>
            <field>Team__c.TotalActivePlayers__c</field>
            <operation>equals</operation>
            <value>11</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <description>Represents Home Team vs Visitor scores</description>
    <label>Score</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>StartDateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Visitors__c.field-meta.xml
<CustomField>
    <fullName>Visitors__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visitors</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team must have 11 active players.</errorMessage>
        <filterItems>
            <field>Team__c.TotalActivePlayers__c</field>
            <operation>equals</operation>
            <value>11</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Visitors)</relationshipLabel>
    <relationshipName>Matches1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <description>A person who plays soccer</description>
    <label>Player</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>The team where the player makes his duties</description>
    <label>Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/TotalActivePlayers__c.field-meta.xml
<CustomField>
    <fullName>TotalActivePlayers__c</fullName>
    <description>Total number of active players</description>
    <label>TotalActivePlayers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/TotalWins__c.field-meta.xml
<CustomField>
    <fullName>TotalWins__c</fullName>
    <description>Total wins of the team</description>
    <label>TotalWins</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SoccerServicesTest.cls
@isTest
private class SoccerServicesTest {

    @TestSetup
    static void dataSetup(){

        Player__c newPlayer1 = new Player__c(Name = 'Player1', Email__c = 'player1@email.com', isActive__c = true);
        Player__c newPlayer2 = new Player__c(Name = 'Player2', Email__c = 'player2@email.com', isActive__c = true);
        insert new List<Player__c>{newPlayer1, newPlayer2};

        Team__c newTeam1 = new Team__c(Name = 'Team1', TotalWins__c = 3, TotalActivePlayers__c = 11);
        Team__c newTeam2 = new Team__c(Name = 'Team2', TotalWins__c = 1, TotalActivePlayers__c = 11);
        insert new List<Team__c>{newTeam1, newTeam2};

        DateTime dt = DateTime.valueOf('2022-11-30 17:00:00');

        Match__c mewMatch1 = new Match__c(
            Name = 'Team1 - Team2', StartDateTime__c = dt, HomeTeam__c = newTeam1.Id, Visitors__c = newTeam2.Id
        );
        insert new List<Match__c>{mewMatch1};
    }

    @isTest
    static void createPlayerTest(){

        String name = 'Player3';
        String email = 'player3@email.com';
        Map<SObjectField, Object> extraValues = new Map<SObjectField, Object>();
        Schema.SObjectField statusField = Player__c.isActive__c;
        Object isActiveStatus = true;
        extraValues.put(statusField, isActiveStatus);

        Test.startTest();
        SoccerService.createPlayer(name, email, extraValues);
        Test.stopTest();

        Player__c createdPlayer = [
            SELECT Name, Email__c
            FROM Player__c
            WHERE Name = 'Player3' AND Email__c = 'player3@email.com'
        ];

        System.assertEquals(
            'player3@email.com',
            createdPlayer.Email__c, 
            'SoccerServices.createPlayer is working incorrectly'
        );
    }

    @isTest
    static void arangeMatchTest(){

        List<Team__c> teamsList = [
            SELECT Id, Name 
            FROM Team__c 
            ORDER BY Name ASC
        ];

        Id homeTeamId = teamsList.get(0).Id;
        Id visitorsTeamId = teamsList.get(1).Id;
        DateTime mathcDT = DateTime.valueOf('2022-12-30 17:00:00');

        Test.startTest();
        SoccerService.arangeMatch(mathcDT, homeTeamId, visitorsTeamId);
        Test.stopTest();

        Match__c createdMatch = [
            SELECT Name, StartDateTime__c, HomeTeam__c, Visitors__c 
            FROM Match__c 
            WHERE StartDateTime__c =: mathcDT
              
        ];

        System.assert(
            createdMatch.StartDateTime__c == mathcDT && createdMatch.HomeTeam__c == homeTeamId && createdMatch.Visitors__c == visitorsTeamId, 
            'SoccerServices.arangeMatch is working incorrectly'
        );
    }

    @isTest
    static void setScoreToMatchesTest(){

        Match__c matchToUpdate = [
            SELECT Id, Name, StartDateTime__c, HomeTeam__c, Visitors__c 
            FROM Match__c 
            WHERE Name =: 'Team1 - Team2'  
        ];

        Id matchId = matchToUpdate.Id;
        Integer homeTeamScore = 2;
        Integer visitorsTeamScore = 1;

        List<SoccerService.ScoreHelper> scoresList = SoccerService.getList(matchId, homeTeamScore, visitorsTeamScore);

        Test.startTest();
        SoccerService.setScoreToMatches(scoresList);
        Test.stopTest();

        Match__c updatedMatch = [
            SELECT Id, Name, StartDateTime__c, HomeTeam__c, Visitors__c, Score__c 
            FROM Match__c 
            WHERE Id =: matchId  
        ];

        System.assertEquals(
            '2:1',
            updatedMatch.Score__c, 
            'SoccerServices.setScoreToMatches is working incorrectly'
        );
    }

    @isTest
    static void deactivatePlayersTest(){

        List<Player__c> playersToDeactivate = [
            SELECT Id, isActive__c
            FROM Player__c
            WHERE isActive__c = true
            LIMIT 2
        ];
        
        Id player1Id = playersToDeactivate.get(0).Id;
        Id player2Id = playersToDeactivate.get(1).Id;

        Test.startTest();
        SoccerService.deactivatePlayers(new List<Id>{player1Id, player2Id});
        Test.stopTest();

        List<Player__c> deactivatedPlayers = [
            SELECT Id, isActive__c
            FROM Player__c
            WHERE isActive__c = false
        ];

        System.assert(
            deactivatedPlayers[0].isActive__c == false && deactivatedPlayers[1].isActive__c == false, 
            'SoccerServices.deactivatePlayers is working incorrectly'
        );
    }
}