force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <description>Soccer match</description>
    <label>Match</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/HomeTeam__c.field-meta.xml
<CustomField>
    <fullName>HomeTeam__c</fullName>
    <label>HomeTeam</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team must have 11 active players.</errorMessage>
        <filterItems>
            <field>Team__c.TotalActivePlayers__c</field>
            <operation>equals</operation>
            <value>11</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <description>Represents Home Team vs Visitor scores</description>
    <label>Score</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>StartDateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Visitors__c.field-meta.xml
<CustomField>
    <fullName>Visitors__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visitors</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team must have 11 active players.</errorMessage>
        <filterItems>
            <field>Team__c.TotalActivePlayers__c</field>
            <operation>equals</operation>
            <value>11</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Visitors)</relationshipLabel>
    <relationshipName>Matches1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <description>A person who plays soccer</description>
    <label>Player</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>The team where the player makes his duties</description>
    <label>Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SoccerService.cls
public with sharing class SoccerService {
	
	public class ScoreHelper{
        Id matchId;
        Integer homeTeamScore;
        Integer visitorsTeamScore;

        public ScoreHelper(String mId, Integer hTeamScore, Integer vTeamScore){
      		this.matchId = mId;
            this.homeTeamScore = hTeamScore;
            this.visitorsTeamScore = vTeamScore;
        }
    }
    
    public static List<ScoreHelper> getList(Id mId, Integer hTeamScore, Integer vTeamScore){
        ScoreHelper newObj = new ScoreHelper(mId, hTeamScore, vTeamScore);
		List<ScoreHelper> scores = new List<ScoreHelper>();
        scores.add(newObj);
        return scores;
    }
    
    public static void createPlayer(String name, String email, Map<SObjectField, Object> extraValues){
        Player__c newPlayer = new Player__c(Name = name, Email__c = email);
        Set<SObjectField> mapKeys = extraValues.keySet();
        List<Object> mapValues = extraValues.values();
        Schema.SObjectField newKey;
        Object newKeyStatus = mapValues[0];

        for (SObjectField key : mapKeys){
            newKey = key;
        }

        newPlayer.put(newKey, newKeyStatus);
        
        try {
            insert newPlayer;
        } catch (System.DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
        }
    }

    public static void arangeMatch(DateTime dt, Id homeTeamId, Id visitorsTeamId){
        Team__c homeTeam = [
            SELECT Name 
            FROM Team__c
            WHERE Id =: homeTeamId  
        ];
        Team__c visitorsTeam = [
            SELECT Name 
            FROM Team__c
            WHERE Id =: visitorsTeamId  
        ];

        Match__c newMatch = new Match__c(
            Name = homeTeam.Name + ' - ' + visitorsTeam.Name,
            StartDateTime__c = dt,
            HomeTeam__c = homeTeamId,
            Visitors__c = visitorsTeamId
        );

        try {
            insert newMatch;
        } catch (System.DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
        }
    }

    public static void setScoreToMatches(List<ScoreHelper> scores){
        String matchId;
        String homeTeamScore;
        String visitorsTeamScore;
        
        for(ScoreHelper a : scores) {
            matchId = String.valueOf(a.matchId);
            homeTeamScore = String.valueOf(a.homeTeamScore);
            visitorsTeamScore = String.valueOf(a.visitorsTeamScore);
    	}
        
        String matchScore = homeTeamScore + ':' + visitorsTeamScore;

        Match__c match = [
            SELECT Name, StartDateTime__c, HomeTeam__c, Visitors__c, Score__c 
            FROM Match__c 
            WHERE Id =: matchId
        ];

        match.Score__c = matchScore;

        try {
            update match;
        } catch (System.DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
        }
    }

    public static void deactivatePlayers(List<Id> playersIds){
        List<Player__c> deactivatedPlayersList = [
            SELECT Name, isActive__c 
            FROM Player__c 
            WHERE Id IN: playersIds
        ];

        for(Player__c player : deactivatedPlayersList){
            player.isActive__c = false;
        }

        try {
            update deactivatedPlayersList;
        } catch (System.DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
        }
    }
}