force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <description>Soccer match</description>
    <label>Match</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/HomeTeam__c.field-meta.xml
<CustomField>
    <fullName>HomeTeam__c</fullName>
    <label>HomeTeam</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team must have 11 active players.</errorMessage>
        <filterItems>
            <field>Team__c.TotalActivePlayers__c</field>
            <operation>equals</operation>
            <value>11</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>StartDateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Visitors__c.field-meta.xml
<CustomField>
    <fullName>Visitors__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visitors</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team must have 11 active players.</errorMessage>
        <filterItems>
            <field>Team__c.TotalActivePlayers__c</field>
            <operation>equals</operation>
            <value>11</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Visitors)</relationshipLabel>
    <relationshipName>Matches1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Winner__c.field-meta.xml
<CustomField>
    <fullName>Winner__c</fullName>
    <formula>IF( LEFT( Score__c , 1)  &gt;  RIGHT( Score__c , 1)  ,  HomeTeam__r.Name  ,
IF( LEFT( Score__c , 1)  &lt;  RIGHT( Score__c , 1)  ,  Visitors__r.Name ,
IF( LEFT( Score__c , 1)  =  RIGHT( Score__c , 1)  ,  &apos;Draw&apos;  ,
NULL)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Winner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <description>A person who plays soccer</description>
    <label>Player</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>The team where the player makes his duties</description>
    <label>Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PlayerBonusBatch.cls
public class PlayerBonusBatch implements Database.Batchable<sObject>, Schedulable, Database.Stateful {
    
    public Integer recordsProcessed = 0;

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id, Name, StartDatetime__c, Visitors__c, HomeTeam__c, Winner__c ' + 
            'FROM Match__c ' +
            'WHERE Winner__c != \'Draw\''
        ); //WHERE StartDatetime__c = LAST_N_MONTHS:1
    }
    
    public void execute(Database.BatchableContext bc, List<Match__c> scope){

        Set<Id> teamIds = new Set<Id>();

        for(Match__c match : scope){
            teamIds.add(match.HomeTeam__c);
            teamIds.add(match.Visitors__c);
        }

        List<Player__c> playersList = [
            SELECT Id, Name, isActive__c, Team__c, Bonus__c
            FROM Player__c
            WHERE isActive__c = true AND Team__c IN: teamIds
        ];

        List<Team__c> teamsList = [
            SELECT Id, Name
            FROM Team__c
            WHERE Id IN: teamIds
        ];

        String winerTeamId;

        for(Player__c player : playersList){
            for(Match__c match : scope){
                for(Team__c team : teamsList){
                    if(match.Winner__c == team.Name){
                    	winerTeamId =  team.Id;
                    } 
                }

                if(player.Team__c == winerTeamId){
                    player.Bonus__c += 50;
                }
            }
            ++recordsProcessed;
        }

        update playersList;
    }

    public void finish(Database.BatchableContext bc){
        System.debug(recordsProcessed + ' records processed.');
    }

    public void execute(SchedulableContext context){
        PlayerBonusBatch playerBonus = new PlayerBonusBatch();
        Id batchId = Database.executeBatch(playerBonus);
    }
}