force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <description>Soccer match</description>
    <label>Match</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/HomeTeam__c.field-meta.xml
<CustomField>
    <fullName>HomeTeam__c</fullName>
    <label>HomeTeam</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team must have 11 active players.</errorMessage>
        <filterItems>
            <field>Team__c.TotalActivePlayers__c</field>
            <operation>equals</operation>
            <value>11</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Visitors__c.field-meta.xml
<CustomField>
    <fullName>Visitors__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visitors</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team must have 11 active players.</errorMessage>
        <filterItems>
            <field>Team__c.TotalActivePlayers__c</field>
            <operation>equals</operation>
            <value>11</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Visitors)</relationshipLabel>
    <relationshipName>Matches1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Winner__c.field-meta.xml
<CustomField>
    <fullName>Winner__c</fullName>
    <formula>IF( LEFT( Score__c , 1)  &gt;  RIGHT( Score__c , 1)  ,  HomeTeam__r.Name  ,
IF( LEFT( Score__c , 1)  &lt;  RIGHT( Score__c , 1)  ,  Visitors__r.Name ,
IF( LEFT( Score__c , 1)  =  RIGHT( Score__c , 1)  ,  &apos;Draw&apos;  ,
NULL)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Winner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <description>A person who plays soccer</description>
    <label>Player</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>The team where the player makes his duties</description>
    <label>Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/TotalActivePlayers__c.field-meta.xml
<CustomField>
    <fullName>TotalActivePlayers__c</fullName>
    <description>Total number of active players</description>
    <label>TotalActivePlayers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/TotalWins__c.field-meta.xml
<CustomField>
    <fullName>TotalWins__c</fullName>
    <description>Total wins of the team</description>
    <label>TotalWins</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SoccerDAO.cls
public class SoccerDAO {

    public static List<Team__c> getTeamsByIds(Set<Id> teamIds){
        List<Team__c> teamsList = [SELECT Name FROM Team__c WHERE Id in:teamIds];
        return teamsList;
    }

    public static List<Player__c> getActivePlayers(Integer limitNumber, Integer offsetNumber){
        List<Player__c> activePlayersList = [
            SELECT Name, IsActive__c 
            FROM Player__c 
            WHERE IsActive__c = true 
            ORDER BY Name ASC LIMIT :limitNumber OFFSET :offsetNumber];
        return activePlayersList;
    }

    public static Team__c getMostWinnerTeam(){
        return [SELECT Name FROM Team__c ORDER BY TotalWins__c DESC LIMIT 1];
    }

    public static Integer getWonMatchesCountByTeamId(Id teamId){
        List<Team__c> WonMatchesList = [SELECT TotalWins__c FROM Team__c WHERE Id =: teamId];
        return WonMatchesList[0].TotalWins__c.intValue();    
    }

    public static Map<Id, Integer> getTeamsWithPlayerNumber (Set<Id> teamIds){
        Map<Id, Integer> numberOfPlayers = new Map<Id, Integer>();
        Set<Id> nullTeamIds = new Set<Id>{null};
        if (teamIds == nullTeamIds){
            List<AggregateResult> numberOfPlayersList = Database.query('SELECT COUNT(Id) numberOfPlayers, Team__c '
                + 'FROM Player__c ' + 'WHERE Team__c != null ' + 'GROUP By Team__c');
          	for (AggregateResult a : numberOfPlayersList){
            	String teamId =(String)a.get('Team__c');
            	Integer intdata =(Integer)a.get('numberOfPlayers');
            	numberOfPlayers.put(teamId, intdata);
        	}
        } else {
            List<AggregateResult> numberOfPlayersList = [
                SELECT COUNT(Id) numberOfPlayers, Team__c 
                FROM Player__c 
                WHERE Team__c IN : teamIds GROUP By Team__c
            ];
            for (AggregateResult a : numberOfPlayersList){
            	String teamId =(String)a.get('Team__c');
            	Integer intdata =(Integer)a.get('numberOfPlayers');
            	numberOfPlayers.put(teamId, intdata);
        	}
        }
        
        return numberOfPlayers;
    }

    public static Integer getTeamStatistics(Set<Id> teamIds){
        Set<Id> nullTeamIds = new Set<Id>{null};
        Integer intVersion;
        if (teamIds == nullTeamIds){
            AggregateResult[] avgNumberOfPlayersList = [
                SELECT AVG(TotalActivePlayers__c) avgNumberOfPlayers 
                FROM Team__c 
            ];
            for (AggregateResult a : avgNumberOfPlayersList){
            	Decimal avgdata =(Decimal) a.get('avgNumberOfPlayers');
            	intVersion = Integer.valueOf(avgdata);
        	}
        } else {
            AggregateResult[] avgNumberOfPlayersList = [
                SELECT AVG(TotalActivePlayers__c) avgNumberOfPlayers 
                FROM Team__c 
                WHERE Id IN : teamIds
            ];
            for (AggregateResult a : avgNumberOfPlayersList){
            	Decimal avgdata =(Decimal) a.get('avgNumberOfPlayers');
            	intVersion = Integer.valueOf(avgdata);
        	}
        }
        return intVersion;
    }

    public static Team__c getTeamWithMostScores(){
        List<Match__c> matchesList = [SELECT Winner__c, HomeTeam__c, Visitors__c FROM Match__c ORDER BY Winner__c];
        Map<Id, Integer> teamsScore = new Map<Id, Integer>();
    	
        String homeTeam;
        String visitorTeam;
        String winerTeam;
        Integer homeTeamScore = 0;
        Integer visitorTeamScore = 0;
    	Integer initialScore = 0;
    
    	List<Team__c> allTeamsList = [SELECT Id, Name FROM Team__c];
    	for(Team__c a : allTeamsList){
        	teamsScore.put(a.Id, initialScore);
    	}

		String winerTeamId;
    	
        for(Match__c a : matchesList){
            homeTeam = a.HomeTeam__c;
            visitorTeam = a.Visitors__c;

            if(a.Winner__c != 'Draw'){
                for(Team__c b : allTeamsList){
                    if(a.Winner__c == b.Name){
                    	winerTeamId =  b.Id;
                    } 
                }
               winerTeam = winerTeamId;
            }
            
            if (winerTeam == homeTeam){
                Integer value = teamsScore.get(winerTeam);
                homeTeamScore = value + 2;
                teamsScore.remove(winerTeam);
                teamsScore.put(winerTeam, homeTeamScore);
            } else if (winerTeam == visitorTeam){
                Integer value = teamsScore.get(winerTeam);
                visitorTeamScore = value + 2;
                teamsScore.remove(winerTeam);
                teamsScore.put(winerTeam, visitorTeamScore);
            } else {
                Integer valueHome = teamsScore.get(homeTeam);
                Integer valueVisitors = teamsScore.get(visitorTeam);
                homeTeamScore = valueHome + 1;
                visitorTeamScore = valueVisitors + 1;
                teamsScore.remove(homeTeam);
                teamsScore.remove(visitorTeam);
                teamsScore.put(homeTeam, homeTeamScore);
                teamsScore.put(visitorTeam, visitorTeamScore);
            } 
        }
		System.debug(teamsScore);
        return [SELECT Name FROM Team__c WHERE Id =: winerTeam];
    }
}